language: node_js
node_js:
  - "4.0"
services:
  - redis
before_install:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb -y --force-yes
  - rethinkdb --version
before_script:
  - sudo rethinkdb --daemon
  - npm install
  - sleep 10
script:
  - npm coverage
after_script:
  - killall rethinkdb
  - ./node_modules/.bin/coveralls < ./coverage/lcov.info
