language: node
node_js:
  - "4.0"
sudo: false
services:
  - redis
install:
  - npm install
before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - ulimit -S -n 2048
  - sleep 10
script:
  - npm test
after_script:
  - killall rethinkdb
addons:
  apt:
    sources:
      - ppa:rethinkdb/ppa
    packages:
      - python-software-properties
      - rethinkdb
